<form action="storeWebhook" method="POST" > 
    <table>
        <tr>
            <td>
                webhook name
            </td>
            <td>
                <input name="webhookName" type="text" >
            </td>
        </tr>
        <tr>
            <td>
                event name
            </td>
            <td>
                <input name="eventName" type="text" >
            </td>
        </tr>
        <tr>
            <td>
                key 
            </td>
            <td>
                <input name="key" type="text" >
            </td>
        </tr>
        <tr>
            <td>
                <button name="webhookBtn" type="submit" >ADD</button>
            </td>
        </tr>
    </table>
</form>