<form action="auth" method="GET">
    <table>
        <tr>
            <td>
                email
            </td>
            <td>
                <input name="email" type="email">
            </td>
        </tr>
        <tr>
            <td>
                password
            </td>
            <td>
                <input name="password" type="password">
            </td>
        </tr>
        <tr>
            <td>
                <button type="submit" name="login_btn">log in</button>
            </td>
        </tr>
    </table>
</form>